(defun triangle (num) 
(cond 
((or (not (integerp num)) (zerop num)) (print "input invalid; please enter a positive or a negative integer"))
((< num 0)
(dotimes (n (abs num)) 
(dotimes (p n)
(princ #\space))
(dotimes (k (- (abs num) n)) 
(write '*)
)
(fresh-line)
)
)
(t
(dotimes (n num) 
(dotimes (k (- num n)) 
(write '*) 
)
(fresh-line)
)
)
)
 )

