CC=gcc
CFLAG=-I
binaries =  Question1 Question2 Question3

CPart: 
	$(CC) question-1.c -o Question1
	$(CC) question-2.c -o Question2 
	$(CC) question-3.c -o Question3

.PHONY: clean

clean:
	rm -f $(binaries) *.o
